name: Run Preprocessing

on:
  push:
    paths:
      - "dataset_raw/**"
      - "Preprocessing/**"

jobs:
  preprocessing:
    uses: ./.github/workflows/preprocess_reusable.yml
    with:
      input_path: dataset_raw/car_evaluation.csv
      output_dir: Preprocessing/dataset_preprocessing
      target_column: class
